name: Force deploy by owner commit

on:
  push:
    branches:
      - main

jobs:
  re-commit:
    # Agar commit egasi siz bo'lsa (masalan hikmatilla), workflow SKIP qilinsin
    if: github.actor != 'lastforever457' # â† bu yerga GitHub username'ingizni yozing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Config Git
        run: |
          git config --global user.name "lastforever457"  # sizning nomingiz
          git config --global user.email "lastforever457@gmail.com" # emailingiz

      - name: Update deploy file
        run: |
          echo "Last deploy: $(date)" > deploy.txt
          git add deploy.txt
          git commit -m "Auto deploy trigger" || echo "No changes"

      - name: Push as Owner
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
